Feature/crypto byte finalized
mudasiri/stock-byte pull request #2
Opened 2023-03-16 03:50 UTC by mudasiri

In this Pull Request I have built the following in line with the objectives of the project:

    1. Properly Documented the Project
    2. Used React components
    3. Used React props.
    4. Use React Router.
    5. Connected  React and Redux.
    6. Handle events in the app to navigate user to detail page and back.
    7. Wrote integration tests using React testing library.
    8. Used CSS styles in app.
    9. Used React life cycle methods like useEffect().
    10. Applied React best practices and language style guides in code.
    11. Used store, actions and reducers through SLicers.

A Loom recording of Project is [here](https://www.loom.com/share/37ab72b4ccd041fe849092378257bad8)

2023-03-16 05:19 UTC, OLIPLICHE requested changes
Hi @mudasiri, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Linter is green (the last commit has a green check mark (✅)) 👏
- Commit messages are meaningful 👏 👏
- Gitflow is correctly used👏 👏

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 05:19 UTC, OLIPLICHE commented on README.md
> +- [Live Demo Link](https://cryptobyte-react-app.onrender.com)
- Hi, I would advise you to provide the proper Link to the deployed project. Here is what I am getting. Your ReadMe is the first contact between your project and a visitor. Therefore, leaving this link as it is will not show professionalism. 
![Capture1](https://user-images.githubusercontent.com/63972670/225514122-a94bdcdb-ac34-4cd3-89e0-bbb46c5cdd4a.PNG)

2023-03-16 05:19 UTC, OLIPLICHE commented on README.md
> +I would like to thank Nelson Sakwa for a good ui design on behance which was used as a UI guide for this project.
- I would advise you to Link **Nelson Sakwa** to his website page. It is the best way to acknowledge the author of a website or App design.
- Example: [Nelson Sakwaa](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)),

2023-03-16 05:19 UTC, OLIPLICHE commented on src/App.css
> +
- [ ] **Design**:
- In reading the project requirement, I would advise you to follow the [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)) including:
The Layout: **composition and space between elements**.
Typography: font face, size, and weight.

- [ ] See your design: **Home page**
![Capture](https://user-images.githubusercontent.com/63972670/225519214-46d31730-15a9-4292-b28e-206e17ddba49.PNG)

- [ ] The Original design: **Home and Detail**


![Capture1](https://user-images.githubusercontent.com/63972670/225519577-5780b8ed-05e3-454f-8974-b31507564840.PNG)

2023-03-16 05:19 UTC, OLIPLICHE commented on src/tests/__snapshots__/app.test.js
> +});
- [ ] Testing: In reading the requirement of your Project, I noticed that your testing did not cover 100% of the requirements. Therefore, I would advise you to:
- to write the unit tests for several components of the app and some pure functions in Redux code.
- to write integration tests using React Testing Library. 

- [ ] I know you can make it, keep trying 💪 

![Capture](https://user-images.githubusercontent.com/63972670/225521760-7316b662-3633-4d3e-a2cc-d892bd002252.PNG)

2023-03-18 00:45 UTC, topeogunleye approved these changes
### Hi @mudasiri, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good description :heavy_check_mark:
 
## [Optional] suggestions:
* [ ]  Please check my inline comments.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-18 00:56 UTC, merged